/** Loaded Tea menu flavors sourced from client menu posters. */

export const FLAVOR_COLLECTIONS = [
  {
    slug: 'signature-favourites',
    name: 'Signature Favourites',
    description: 'Loaded Tea classics from the Signature Favorites menu (posters 1–3).',
  },
  {
    slug: 'new-flavour-collection',
    name: 'New Flavour Collection',
    description: 'Latest loaded tea blends from the New Flavor Collection menu (posters 4–7).',
  },
  {
    slug: 'fall-citrus-collection',
    name: 'Fall Citrus Collection',
    description: 'Bright citrus seasonal blends (menu poster 1).',
  },
  {
    slug: 'fall-berry-collection',
    name: 'Fall Berry Collection',
    description: 'Seasonal berry-forward blends (menu posters 2 & 4).',
  },
  {
    slug: 'school-fun-collection',
    name: 'School Fun Collection',
    description: 'Playful school-inspired blends (menu poster 3).',
  },
] as const;

/** Client batch-2 poster index (1–4) → collection. */
export const SEASONAL_POSTER_MAP = [
  { imageIndex: 1, collection: 'fall-citrus-collection' },
  { imageIndex: 2, collection: 'fall-berry-collection' },
  { imageIndex: 3, collection: 'school-fun-collection' },
  { imageIndex: 4, collection: 'fall-berry-collection' },
] as const;

export type FlavorCollectionSlug = (typeof FLAVOR_COLLECTIONS)[number]['slug'];

export interface MenuFlavor {
  slug: string;
  name: string;
  collection: FlavorCollectionSlug;
  color: string;
  isNew: boolean;
  ingredients: readonly string[];
}

export const MENU_FLAVORS: readonly MenuFlavor[] = [
  {
    slug: 'citrus-watermelon-surge',
    name: 'Citrus Watermelon Surge',
    collection: 'signature-favourites',
    color: '#E8F000',
    isNew: false,
    ingredients: ['Lemon-lime', 'Lemon', 'Mandarin', 'Watermelon', 'Lime'],
  },
  {
    slug: 'raspberry-pineapple-spark',
    name: 'Raspberry Pineapple Spark',
    collection: 'signature-favourites',
    color: '#FF3F72',
    isNew: false,
    ingredients: ['Lemon-lime', 'Raspberry', 'Cranberry', 'Watermelon', 'Pineapple'],
  },
  {
    slug: 'ruby-raspberry-wave',
    name: 'Ruby Raspberry Wave',
    collection: 'signature-favourites',
    color: '#FFE500',
    isNew: false,
    ingredients: ['Pomegranate', 'Raspberry', 'Cranberry', 'Watermelon'],
  },
  {
    slug: 'green-apple-mango-splash',
    name: 'Green Apple Mango Splash',
    collection: 'signature-favourites',
    color: '#CDDC39',
    isNew: false,
    ingredients: ['Lemon-lime', 'Lemon', 'Mango', 'Watermelon', 'Green apple'],
  },
  {
    slug: 'rainbow-watermelon-carnival',
    name: 'Rainbow Watermelon Carnival',
    collection: 'signature-favourites',
    color: '#FF4081',
    isNew: false,
    ingredients: ['Tropical fruit', 'Mandarin', 'Watermelon', 'Rainbow candy'],
  },
  {
    slug: 'sunshine-strawberry-splash',
    name: 'Sunshine Strawberry Splash',
    collection: 'signature-favourites',
    color: '#A4C639',
    isNew: false,
    ingredients: ['Tropical Liftoff', 'Lemon Tea', 'Lemon', 'Strawberry'],
  },
  {
    slug: 'pink-colada-cruiser',
    name: 'Pink Colada Cruiser',
    collection: 'signature-favourites',
    color: '#E8F000',
    isNew: false,
    ingredients: ['Orange Liftoff', 'Lemon Tea', 'Pink candy', 'Pina colada'],
  },
  {
    slug: 'mango-hibiscus-sunset',
    name: 'Mango Hibiscus Sunset',
    collection: 'signature-favourites',
    color: '#FF3F72',
    isNew: false,
    ingredients: ['Pomegranate', 'Passionfruit hibiscus', 'Mango', 'Watermelon', 'Lime'],
  },
  {
    slug: 'cherry-watermelon-rush',
    name: 'Cherry Watermelon Rush',
    collection: 'signature-favourites',
    color: '#FFE500',
    isNew: false,
    ingredients: ['Pomegranate', 'Lemon', 'Cranberry', 'Watermelon', 'Cherry'],
  },
  {
    slug: 'strawberry-hibiscus-glow',
    name: 'Strawberry Hibiscus Glow',
    collection: 'signature-favourites',
    color: '#CDDC39',
    isNew: false,
    ingredients: ['Tropical fruit', 'Passionfruit hibiscus', 'Cranberry', 'Watermelon', 'Strawberry'],
  },
  {
    slug: 'pineapple-passion-sunset',
    name: 'Pineapple Passion Sunset',
    collection: 'signature-favourites',
    color: '#FF4081',
    isNew: false,
    ingredients: ['Pineapple', 'Passionfruit hibiscus', 'Mango', 'Watermelon'],
  },
  {
    slug: 'witches-whip',
    name: 'Witches Whip',
    collection: 'signature-favourites',
    color: '#A4C639',
    isNew: false,
    ingredients: ['Lemon-Lime Liftoff', 'Raspberry Tea', 'Grape Aloe', 'Green apple', 'Grape', 'Blue Blast'],
  },
  {
    slug: 'cherry-cotton-candy-buzz',
    name: 'Cherry Cotton Candy Buzz',
    collection: 'signature-favourites',
    color: '#E8F000',
    isNew: false,
    ingredients: ['Tropical Liftoff', 'Raspberry Tea', 'Cherry limeade', 'Cotton candy'],
  },
  {
    slug: 'blue-citrus-breeze',
    name: 'Blue Citrus Breeze',
    collection: 'signature-favourites',
    color: '#FF3F72',
    isNew: false,
    ingredients: ['Orange Liftoff', 'Peach Tea', 'Blue raspberry citrus', 'Orange'],
  },
  {
    slug: 'pink-lime-spark',
    name: 'Pink Lime Spark',
    collection: 'signature-favourites',
    color: '#FFE500',
    isNew: false,
    ingredients: ['Lime Liftoff', 'Raspberry Tea', 'Pink lemonade'],
  },
  {
    slug: 'raspberry-citrus-rush',
    name: 'Raspberry Citrus Rush',
    collection: 'signature-favourites',
    color: '#CDDC39',
    isNew: false,
    ingredients: ['Pomegranate Liftoff', 'Raspberry Tea', 'Orange', 'Raspberry'],
  },
  {
    slug: 'blueberry-boardwalk-splash',
    name: 'Blueberry Boardwalk Splash',
    collection: 'signature-favourites',
    color: '#FF4081',
    isNew: false,
    ingredients: ['Lemon-Lime Liftoff', 'Raspberry Tea', 'Strawberry-watermelon', 'Blue raspberry', 'Strawberry lemonade', 'Mango Aloe'],
  },
  {
    slug: 'cherry-watermelon-crush',
    name: 'Cherry Watermelon Crush',
    collection: 'signature-favourites',
    color: '#A4C639',
    isNew: false,
    ingredients: ['Pomegranate Berry Liftoff', 'Raspberry Tea', 'Cherry', 'Strawberry-watermelon'],
  },
  {
    slug: 'blackberry-grape-melon',
    name: 'Blackberry Grape Melon',
    collection: 'signature-favourites',
    color: '#E8F000',
    isNew: false,
    ingredients: ['Pomegranate Berry Liftoff', 'Peach Tea', 'Blackberry', 'Strawberry-watermelon', 'Grape Aloe'],
  },
  {
    slug: 'orange-pineapple-paradise',
    name: 'Orange Pineapple Paradise',
    collection: 'signature-favourites',
    color: '#FF3F72',
    isNew: false,
    ingredients: ['Orange Liftoff', 'Peach Tea', 'Tropical fruit', 'Strawberry-watermelon', 'Orange-pineapple', 'Mango Aloe'],
  },
  {
    slug: 'watermelon-lemonade-lift',
    name: 'Watermelon Lemonade Lift',
    collection: 'signature-favourites',
    color: '#FFE500',
    isNew: false,
    ingredients: ['Lemon-Lime Liftoff', 'Raspberry Tea', 'Strawberry-watermelon', 'Strawberry lemonade collagen', 'Cranberry Aloe'],
  },
  {
    slug: 'melon-berry-glow',
    name: 'Melon Berry Glow',
    collection: 'signature-favourites',
    color: '#CDDC39',
    isNew: false,
    ingredients: ['Lime Liftoff', 'Peach Tea', 'Watermelon', 'Strawberry'],
  },
  {
    slug: 'rainbow-grape-pop',
    name: 'Rainbow Grape Pop',
    collection: 'signature-favourites',
    color: '#FF4081',
    isNew: false,
    ingredients: ['Pomegranate Liftoff', 'Peach Tea', 'Rainbow candy', 'Grape'],
  },
  {
    slug: 'electric-watermelon-wave',
    name: 'Electric Watermelon Wave',
    collection: 'signature-favourites',
    color: '#A4C639',
    isNew: false,
    ingredients: ['Lemon-Lime Liftoff', 'Raspberry Tea', 'Blue Blast', 'Strawberry-watermelon'],
  },
  {
    slug: 'tropical-pineapple-melon',
    name: 'Tropical Pineapple Melon',
    collection: 'signature-favourites',
    color: '#E8F000',
    isNew: false,
    ingredients: ['Orange Liftoff', 'Peach Tea', 'Orange-pineapple', 'Strawberry-watermelon', 'Tropical fruit'],
  },
  {
    slug: 'strawberry-lemonade-glow',
    name: 'Strawberry Lemonade Glow',
    collection: 'signature-favourites',
    color: '#FF3F72',
    isNew: false,
    ingredients: ['Lemon-Lime Liftoff', 'Peach Tea', 'Strawberry', 'Strawberry-watermelon', 'Strawberry lemonade collagen'],
  },
  {
    slug: 'rainbow-candy-splash',
    name: 'Rainbow Candy Splash',
    collection: 'signature-favourites',
    color: '#FFE500',
    isNew: false,
    ingredients: ['Pomegranate Berry Liftoff', 'Raspberry Tea', 'Rainbow candy', 'Strawberry-watermelon'],
  },
  {
    slug: 'blackberry-watermelon-burst',
    name: 'Blackberry Watermelon Burst',
    collection: 'signature-favourites',
    color: '#CDDC39',
    isNew: false,
    ingredients: ['Pomegranate Berry Liftoff', 'Raspberry Tea', 'Strawberry-watermelon', 'Blackberry'],
  },
  {
    slug: 'island-cherry-punch',
    name: 'Island Cherry Punch',
    collection: 'signature-favourites',
    color: '#FF4081',
    isNew: false,
    ingredients: ['Orange Liftoff', 'Peach Tea', 'Strawberry-watermelon', 'Orange-pineapple', 'Cherry'],
  },
  {
    slug: 'kiwi-mango-splash',
    name: 'Kiwi Mango Splash',
    collection: 'signature-favourites',
    color: '#A4C639',
    isNew: false,
    ingredients: ['Pineapple Liftoff', 'Strawberry kiwi', 'Mango', 'Mango Aloe'],
  },
  {
    slug: 'coconut-strawberry-breeze',
    name: 'Coconut Strawberry Breeze',
    collection: 'signature-favourites',
    color: '#E8F000',
    isNew: false,
    ingredients: ['Pineapple Liftoff', 'Strawberry', 'Coconut', 'Pineapple'],
  },
  {
    slug: 'mango-melon-express',
    name: 'Mango Melon Express',
    collection: 'signature-favourites',
    color: '#FF3F72',
    isNew: false,
    ingredients: ['Pineapple Liftoff', 'Mango', 'Melon', 'Mango Aloe'],
  },
  {
    slug: 'color-burst',
    name: 'Color Burst',
    collection: 'signature-favourites',
    color: '#FFE500',
    isNew: false,
    ingredients: ['Orange Liftoff', 'Mango Aloe', 'Cherry', 'Grape'],
  },
  {
    slug: 'cherry-citrus-chill',
    name: 'Cherry Citrus Chill',
    collection: 'new-flavour-collection',
    color: '#CDDC39',
    isNew: true,
    ingredients: ['Lemon-Lime Liftoff', 'Raspberry Tea', 'Cherry', 'Limeade', 'Cranberry Aloe'],
  },
  {
    slug: 'tropical-mango-punch',
    name: 'Tropical Mango Punch',
    collection: 'new-flavour-collection',
    color: '#FF4081',
    isNew: true,
    ingredients: ['Orange Liftoff', 'Peach Tea', 'Tropical fruit', 'Orange-pineapple', 'Mango Aloe'],
  },
  {
    slug: 'cotton-candy-berry-pop',
    name: 'Cotton Candy Berry Pop',
    collection: 'new-flavour-collection',
    color: '#A4C639',
    isNew: true,
    ingredients: ['Pomegranate Berry Liftoff', 'Raspberry Tea', 'Rainbow candy', 'Strawberry'],
  },
  {
    slug: 'strawberry-lemon-glow',
    name: 'Strawberry Lemon Glow',
    collection: 'new-flavour-collection',
    color: '#E8F000',
    isNew: true,
    ingredients: ['Lemon-Lime Liftoff', 'Peach Tea', 'Strawberry', 'Strawberry lemonade collagen', 'Cranberry Aloe'],
  },
  {
    slug: 'blackberry-lemon-beauty',
    name: 'Blackberry Lemon Beauty',
    collection: 'new-flavour-collection',
    color: '#FF3F72',
    isNew: true,
    ingredients: ['Pomegranate Berry Liftoff', 'Raspberry Tea', 'Blackberry', 'Strawberry lemonade collagen', 'Wild Berry Mix'],
  },
  {
    slug: 'cherry-paradise-splash',
    name: 'Cherry Paradise Splash',
    collection: 'new-flavour-collection',
    color: '#FFE500',
    isNew: true,
    ingredients: ['Orange Liftoff', 'Peach Tea', 'Tropical fruit', 'Cherry', 'Strawberry'],
  },
  {
    slug: 'watermelon-lime-candy',
    name: 'Watermelon Lime Candy',
    collection: 'new-flavour-collection',
    color: '#CDDC39',
    isNew: true,
    ingredients: ['Lemon-Lime Liftoff', 'Raspberry Tea', 'Strawberry-watermelon', 'Limeade'],
  },
  {
    slug: 'blueberry-grape-lagoon',
    name: 'Blueberry Grape Lagoon',
    collection: 'new-flavour-collection',
    color: '#FF4081',
    isNew: true,
    ingredients: ['Lemon-Lime Liftoff', 'Raspberry Tea', 'Blue Blast', 'Blackberry', 'Grape Aloe'],
  },
  {
    slug: 'strawberry-sunrise-crush',
    name: 'Strawberry Sunrise Crush',
    collection: 'new-flavour-collection',
    color: '#A4C639',
    isNew: true,
    ingredients: ['Orange Liftoff', 'Peach Tea', 'Strawberry', 'Orange-pineapple', 'Peach Mango Mix'],
  },
  {
    slug: 'blue-raspberry-voltage',
    name: 'Blue Raspberry Voltage',
    collection: 'new-flavour-collection',
    color: '#E8F000',
    isNew: true,
    ingredients: ['Lemon-Lime Liftoff', 'Raspberry Tea', 'Blue raspberry', 'Blue Blast'],
  },
  {
    slug: 'pink-citrus-kiss',
    name: 'Pink Citrus Kiss',
    collection: 'new-flavour-collection',
    color: '#FF3F72',
    isNew: true,
    ingredients: ['Lemon-Lime Liftoff', 'Raspberry Tea', 'Strawberry', 'Limeade', 'Strawberry lemonade collagen'],
  },
  {
    slug: 'purple-grape-storm',
    name: 'Purple Grape Storm',
    collection: 'new-flavour-collection',
    color: '#FFE500',
    isNew: true,
    ingredients: ['Pomegranate Berry Liftoff', 'Raspberry Tea', 'Blackberry', 'Blue Blast', 'Grape Aloe'],
  },
  {
    slug: 'strawberry-island-punch',
    name: 'Strawberry Island Punch',
    collection: 'new-flavour-collection',
    color: '#CDDC39',
    isNew: true,
    ingredients: ['Orange Liftoff', 'Peach Tea', 'Tropical fruit', 'Strawberry', 'Orange-pineapple', 'Mango Aloe'],
  },
  {
    slug: 'tropical-melon-sunrise',
    name: 'Tropical Melon Sunrise',
    collection: 'new-flavour-collection',
    color: '#FF4081',
    isNew: true,
    ingredients: ['Orange Liftoff', 'Peach Tea', 'Strawberry-watermelon', 'Tropical fruit', 'Mango Aloe'],
  },
  {
    slug: 'ocean-berry-breeze',
    name: 'Ocean Berry Breeze',
    collection: 'new-flavour-collection',
    color: '#A4C639',
    isNew: true,
    ingredients: ['Lemon-Lime Liftoff', 'Raspberry Tea', 'Blue Blast', 'Tropical fruit', 'Mango Aloe'],
  },
  {
    slug: 'rainbow-lime-shock',
    name: 'Rainbow Lime Shock',
    collection: 'new-flavour-collection',
    color: '#E8F000',
    isNew: true,
    ingredients: ['Lemon-Lime Liftoff', 'Raspberry Tea', 'Rainbow candy', 'Limeade'],
  },
  {
    slug: 'berry-sunset-glow',
    name: 'Berry Sunset Glow',
    collection: 'new-flavour-collection',
    color: '#FF3F72',
    isNew: true,
    ingredients: ['Orange Liftoff', 'Raspberry Tea', 'Strawberry', 'Blackberry', 'Cranberry Aloe'],
  },
  {
    slug: 'clean-citrus-green',
    name: 'Clean Citrus Green',
    collection: 'new-flavour-collection',
    color: '#FFE500',
    isNew: true,
    ingredients: ['Lemon-Lime Liftoff', 'Peach Tea', 'Limeade', 'Cranberry Aloe'],
  },
  {
    slug: 'raspberry-grape-hydration',
    name: 'Raspberry Grape Hydration',
    collection: 'new-flavour-collection',
    color: '#CDDC39',
    isNew: true,
    ingredients: ['Pomegranate Berry Liftoff', 'Raspberry Tea', 'Limeade', 'Grape Aloe'],
  },
  {
    slug: 'tropical-watermelon-rush',
    name: 'Tropical Watermelon Rush',
    collection: 'new-flavour-collection',
    color: '#FF5722',
    isNew: true,
    ingredients: ['Tropical Liftoff', 'Passion Hibiscus NRG', 'Watermelon Hydration', 'Strawberry-Kiwi'],
  },
  {
    slug: 'wild-berry-cheesecake',
    name: 'Wild Berry Cheesecake',
    collection: 'new-flavour-collection',
    color: '#FF4081',
    isNew: true,
    ingredients: ['Pomegranate Berry Liftoff', 'Raspberry Tea', 'Wild Berry Mix', 'Strawberry lemonade collagen'],
  },
  {
    slug: 'cherry-cola-spark',
    name: 'Cherry Cola Spark',
    collection: 'new-flavour-collection',
    color: '#A4C639',
    isNew: true,
    ingredients: ['Pomegranate Berry Liftoff', 'Raspberry Tea', 'Cherry', 'Limeade'],
  },
  {
    slug: 'coral-strawberry-reef',
    name: 'Coral Strawberry Reef',
    collection: 'new-flavour-collection',
    color: '#E8F000',
    isNew: true,
    ingredients: ['Pomegranate Berry Liftoff', 'Peach Tea', 'Tropical fruit', 'Strawberry', 'Grape Aloe'],
  },
  {
    slug: 'tart-blueberry-twist',
    name: 'Tart Blueberry Twist',
    collection: 'new-flavour-collection',
    color: '#FF3F72',
    isNew: true,
    ingredients: ['Pomegranate Berry Liftoff', 'Raspberry Tea', 'Blue raspberry', 'Limeade'],
  },
  {
    slug: 'peach-tropical-lime',
    name: 'Peach Tropical Lime',
    collection: 'new-flavour-collection',
    color: '#FFE500',
    isNew: true,
    ingredients: ['Lemon-Lime Liftoff', 'Peach Tea', 'Tropical fruit', 'Limeade', 'Mango Aloe'],
  },
  {
    slug: 'orange-lime-cooler',
    name: 'Orange Lime Cooler',
    collection: 'new-flavour-collection',
    color: '#CDDC39',
    isNew: true,
    ingredients: ['Orange Liftoff', 'Peach Tea', 'Limeade', 'Mango Aloe'],
  },
  {
    slug: 'strawberry-shortcake-splash',
    name: 'Strawberry Shortcake Splash',
    collection: 'new-flavour-collection',
    color: '#FF4081',
    isNew: true,
    ingredients: ['Orange Liftoff', 'Peach Tea', 'Strawberry', 'Peach Mango Mix', 'Strawberry lemonade collagen'],
  },
  {
    slug: 'fruity-rainbow-pebbles',
    name: 'Fruity Rainbow Pebbles',
    collection: 'new-flavour-collection',
    color: '#A4C639',
    isNew: true,
    ingredients: ['Lemon-Lime Liftoff', 'Peach Tea', 'Rainbow candy', 'Strawberry lemonade collagen'],
  },
  {
    slug: 'grape-blue-fizz',
    name: 'Grape Blue Fizz',
    collection: 'new-flavour-collection',
    color: '#E8F000',
    isNew: true,
    ingredients: ['Lemon-Lime Liftoff', 'Raspberry Tea', 'Grape', 'Blue Blast', 'Grape Aloe'],
  },
  {
    slug: 'citrus-pineapple-twist',
    name: 'Citrus Pineapple Twist',
    collection: 'new-flavour-collection',
    color: '#FF3F72',
    isNew: true,
    ingredients: ['Lemon-Lime Liftoff', 'Peach Tea', 'Orange-pineapple', 'Limeade', 'Mango Aloe'],
  },
  {
    slug: 'sweet-tart-galaxy',
    name: 'Sweet Tart Galaxy',
    collection: 'new-flavour-collection',
    color: '#FFE500',
    isNew: true,
    ingredients: ['Pomegranate Berry Liftoff', 'Raspberry Tea', 'Rainbow candy', 'Blue Blast'],
  },
  {
    slug: 'galaxy-berry-storm',
    name: 'Galaxy Berry Storm',
    collection: 'new-flavour-collection',
    color: '#CDDC39',
    isNew: true,
    ingredients: ['Pomegranate Berry Liftoff', 'Raspberry Tea', 'Blue raspberry', 'Blue Blast', 'Blackberry'],
  },
  {
    slug: 'hawaiian-melon-punch',
    name: 'Hawaiian Melon Punch',
    collection: 'new-flavour-collection',
    color: '#FF4081',
    isNew: true,
    ingredients: ['Orange Liftoff', 'Peach Tea', 'Strawberry-watermelon', 'Tropical fruit', 'Cherry'],
  },
  {
    slug: 'black-cherry-bomb',
    name: 'Black Cherry Bomb',
    collection: 'new-flavour-collection',
    color: '#A4C639',
    isNew: true,
    ingredients: ['Pomegranate Berry Liftoff', 'Raspberry Tea', 'Cherry', 'Blackberry'],
  },
  {
    slug: 'citrus-cherry-fizz',
    name: 'Citrus Cherry Fizz',
    collection: 'new-flavour-collection',
    color: '#E8F000',
    isNew: true,
    ingredients: ['Orange Liftoff', 'Peach Tea', 'Orange-pineapple', 'Cherry', 'Cranberry Aloe'],
  },
  {
    slug: 'watermelon-mango-magic',
    name: 'Watermelon Mango Magic',
    collection: 'new-flavour-collection',
    color: '#FF3F72',
    isNew: true,
    ingredients: ['Lemon-Lime Liftoff', 'Peach Tea', 'Strawberry-watermelon', 'Mango Aloe'],
  },
  {
    slug: 'tropical-blueberry-boost',
    name: 'Tropical Blueberry Boost',
    collection: 'new-flavour-collection',
    color: '#FFE500',
    isNew: true,
    ingredients: ['Orange Liftoff', 'Peach Tea', 'Tropical fruit', 'Blue Blast', 'Wild Berry Mix'],
  },
  {
    slug: 'peach-berry-lime-fizz',
    name: 'Peach Berry Lime Fizz',
    collection: 'new-flavour-collection',
    color: '#CDDC39',
    isNew: true,
    ingredients: ['Orange Liftoff', 'Peach Tea', 'Strawberry', 'Limeade', 'Peach Mango Mix'],
  },
  {
    slug: 'cherry-strawberry-punch',
    name: 'Cherry Strawberry Punch',
    collection: 'new-flavour-collection',
    color: '#FF4081',
    isNew: true,
    ingredients: ['Pomegranate Berry Liftoff', 'Raspberry Tea', 'Cherry', 'Strawberry', 'Wild Berry Mix'],
  },
  {
    slug: 'caribbean-cherry-dream',
    name: 'Caribbean Cherry Dream',
    collection: 'new-flavour-collection',
    color: '#A4C639',
    isNew: true,
    ingredients: ['Orange Liftoff', 'Peach Tea', 'Tropical fruit', 'Cherry', 'Peach Mango Mix'],
  },
  {
    slug: 'mango-blue-splash',
    name: 'Mango Blue Splash',
    collection: 'new-flavour-collection',
    color: '#E8F000',
    isNew: true,
    ingredients: ['Orange Liftoff', 'Peach Tea', 'Tropical fruit', 'Blue Blast', 'Peach Mango Mix'],
  },
  {
    slug: 'pink-panther-punch',
    name: 'Pink Panther Punch',
    collection: 'new-flavour-collection',
    color: '#FF3F72',
    isNew: true,
    ingredients: ['Orange Liftoff', 'Peach Tea', 'Strawberry', 'Cherry', 'Strawberry lemonade collagen'],
  },
  {
    slug: 'wild-berry-wave',
    name: 'Wild Berry Wave',
    collection: 'new-flavour-collection',
    color: '#FFE500',
    isNew: true,
    ingredients: ['Lemon-Lime Liftoff', 'Raspberry Tea', 'Blue raspberry', 'Strawberry', 'Wild Berry Mix'],
  },
  {
    slug: 'sunset-cherry-melon',
    name: 'Sunset Cherry Melon',
    collection: 'new-flavour-collection',
    color: '#CDDC39',
    isNew: true,
    ingredients: ['Orange Liftoff', 'Peach Tea', 'Strawberry-watermelon', 'Cherry', 'Peach Mango Mix'],
  },
  {
    slug: 'wild-island-berry',
    name: 'Wild Island Berry',
    collection: 'new-flavour-collection',
    color: '#FF4081',
    isNew: true,
    ingredients: ['Orange Liftoff', 'Peach Tea', 'Tropical fruit', 'Blue raspberry', 'Wild Berry Mix'],
  },
  {
    slug: 'berry-sunrise-spark',
    name: 'Berry Sunrise Spark',
    collection: 'new-flavour-collection',
    color: '#A4C639',
    isNew: true,
    ingredients: ['Orange Liftoff', 'Peach Tea', 'Strawberry', 'Orange-pineapple', 'Wild Berry Mix'],
  },
  {
    slug: 'berry-candy-crush',
    name: 'Berry Candy Crush',
    collection: 'new-flavour-collection',
    color: '#E8F000',
    isNew: true,
    ingredients: ['Lemon-Lime Liftoff', 'Raspberry Tea', 'Rainbow candy', 'Blue raspberry', 'Wild Berry Mix'],
  },
  {
    slug: 'ultimate-berry-fusion',
    name: 'Ultimate Berry Fusion',
    collection: 'new-flavour-collection',
    color: '#FF3F72',
    isNew: true,
    ingredients: ['Pomegranate Berry Liftoff', 'Raspberry Tea', 'Strawberry', 'Blackberry', 'Wild Berry Mix'],
  },
  {
    slug: 'citrus-grove-glow',
    name: 'Citrus Grove Glow',
    collection: 'fall-citrus-collection',
    color: '#FFE500',
    isNew: false,
    ingredients: ['Orange Liftoff', 'Lemon Tea', 'Orange'],
  },
  {
    slug: 'strawberry-spice-spark',
    name: 'Strawberry Spice Spark',
    collection: 'fall-citrus-collection',
    color: '#CDDC39',
    isNew: false,
    ingredients: ['Orange Liftoff', 'Lemon Tea', 'Strawberry'],
  },
  {
    slug: 'peech-harvest-glow',
    name: 'Peach Harvest Glow',
    collection: 'fall-citrus-collection',
    color: '#FF4081',
    isNew: false,
    ingredients: ['Orange Liftoff', 'Lemon Tea', 'Peach'],
  },
  {
    slug: 'pineapple-gold',
    name: 'Pineapple Gold',
    collection: 'fall-citrus-collection',
    color: '#A4C639',
    isNew: false,
    ingredients: ['Orange Liftoff', 'Lemon Tea', 'Pineapple'],
  },
  {
    slug: 'lemonade-zest',
    name: 'Lemonade Zest',
    collection: 'fall-citrus-collection',
    color: '#E8F000',
    isNew: false,
    ingredients: ['Orange Liftoff', 'Lemon Tea', 'Lemonade'],
  },
  {
    slug: 'mango-morning',
    name: 'Mango Morning',
    collection: 'fall-citrus-collection',
    color: '#FF3F72',
    isNew: false,
    ingredients: ['Orange Liftoff', 'Lemon Tea', 'Mango'],
  },
  {
    slug: 'apple-orchard-spark',
    name: 'Apple Orchard Spark',
    collection: 'fall-citrus-collection',
    color: '#FFE500',
    isNew: false,
    ingredients: ['Orange Liftoff', 'Lemon Tea', 'Apple'],
  },
  {
    slug: 'peech-tea-sunset',
    name: 'Peach Tea Sunset',
    collection: 'fall-citrus-collection',
    color: '#CDDC39',
    isNew: false,
    ingredients: ['Orange Liftoff', 'Lemon Tea', 'Peach tea'],
  },
  {
    slug: 'golden-grape',
    name: 'Golden Grape',
    collection: 'fall-citrus-collection',
    color: '#FF4081',
    isNew: false,
    ingredients: ['Orange Liftoff', 'Lemon Tea', 'Grape'],
  },
  {
    slug: 'tropical-citrus-pop',
    name: 'Tropical Citrus Pop',
    collection: 'fall-citrus-collection',
    color: '#A4C639',
    isNew: false,
    ingredients: ['Orange Liftoff', 'Lemon Tea', 'Tropical punch'],
  },
  {
    slug: 'raspberry-citrus-twist',
    name: 'Raspberry Citrus Twist',
    collection: 'fall-citrus-collection',
    color: '#E8F000',
    isNew: false,
    ingredients: ['Orange Liftoff', 'Lemon Tea', 'Raspberry lemonade'],
  },
  {
    slug: 'peech-mango-hyride',
    name: 'Peach Mango Hayride',
    collection: 'fall-citrus-collection',
    color: '#FF3F72',
    isNew: false,
    ingredients: ['Orange Liftoff', 'Lemon Tea', 'Peach mango'],
  },
  {
    slug: 'cranberry-citrus-thanks',
    name: 'Cranberry Citrus Thanks',
    collection: 'fall-citrus-collection',
    color: '#FFE500',
    isNew: false,
    ingredients: ['Orange Liftoff', 'Lemon Tea', 'Cranberry'],
  },
  {
    slug: 'passion-fruit-fall-fizz',
    name: 'Passionfruit Fall Fizz',
    collection: 'fall-citrus-collection',
    color: '#CDDC39',
    isNew: false,
    ingredients: ['Orange Liftoff', 'Lemon Tea', 'Passion fruit'],
  },
  {
    slug: 'berry-candy-rush',
    name: 'Berry Candy Rush',
    collection: 'fall-citrus-collection',
    color: '#FF4081',
    isNew: false,
    ingredients: ['Loaded tea blend — ingredients available in-store.'],
  },
  {
    slug: 'strawberry-forest-spark',
    name: 'Strawberry Forest Spark',
    collection: 'fall-berry-collection',
    color: '#A4C639',
    isNew: false,
    ingredients: ['Blackberry Liftoff', 'Raspberry Tea', 'Strawberry'],
  },
  {
    slug: 'mix-berry-bramble',
    name: 'Mixed Berry Bramble',
    collection: 'fall-berry-collection',
    color: '#E8F000',
    isNew: false,
    ingredients: ['Blackberry Liftoff', 'Raspberry Tea', 'Mixed berry'],
  },
  {
    slug: 'chrimson-cherry-trail',
    name: 'Crimson Cherry Trail',
    collection: 'fall-berry-collection',
    color: '#FF3F72',
    isNew: false,
    ingredients: ['Blackberry Liftoff', 'Raspberry Tea', 'Cherry'],
  },
  {
    slug: 'harvest-noir',
    name: 'Harvest Noir',
    collection: 'fall-berry-collection',
    color: '#FFE500',
    isNew: false,
    ingredients: ['Blackberry Liftoff', 'Raspberry Tea', 'Black cherry'],
  },
  {
    slug: 'wildwood-berry',
    name: 'Wildwood Berry',
    collection: 'fall-berry-collection',
    color: '#CDDC39',
    isNew: false,
    ingredients: ['Blackberry Liftoff', 'Raspberry Tea', 'Wild berry'],
  },
  {
    slug: 'blueberry-bonfire',
    name: 'Blueberry Bonfire',
    collection: 'fall-berry-collection',
    color: '#FF4081',
    isNew: false,
    ingredients: ['Blackberry Liftoff', 'Raspberry Tea', 'Blue raspberry'],
  },
  {
    slug: 'raspberry-cider-pop',
    name: 'Raspberry Cider Pop',
    collection: 'fall-berry-collection',
    color: '#A4C639',
    isNew: false,
    ingredients: ['Blackberry Liftoff', 'Raspberry Tea', 'Raspberry lemonade'],
  },
  {
    slug: 'cranberry-canopy',
    name: 'Cranberry Canopy',
    collection: 'fall-berry-collection',
    color: '#E8F000',
    isNew: false,
    ingredients: ['Blackberry Liftoff', 'Raspberry Tea', 'Cranberry'],
  },
  {
    slug: 'grape-twilight',
    name: 'Grape Twilight',
    collection: 'fall-berry-collection',
    color: '#FF3F72',
    isNew: false,
    ingredients: ['Blackberry Liftoff', 'Raspberry Tea', 'Grape'],
  },
  {
    slug: 'apple-brumble',
    name: 'Apple Bramble',
    collection: 'fall-berry-collection',
    color: '#FFE500',
    isNew: false,
    ingredients: ['Blackberry Liftoff', 'Raspberry Tea', 'Apple'],
  },
  {
    slug: 'tropical-berry-tail',
    name: 'Tropical Berry Trail',
    collection: 'fall-berry-collection',
    color: '#CDDC39',
    isNew: false,
    ingredients: ['Blackberry Liftoff', 'Raspberry Tea', 'Tropical punch'],
  },
  {
    slug: 'peech-mango-hearth',
    name: 'Peach Mango Hearth',
    collection: 'fall-berry-collection',
    color: '#FF4081',
    isNew: false,
    ingredients: ['Blackberry Liftoff', 'Raspberry Tea', 'Peach mango'],
  },
  {
    slug: 'lemonade-berry-fizz',
    name: 'Lemonade Berry Fizz',
    collection: 'fall-berry-collection',
    color: '#A4C639',
    isNew: false,
    ingredients: ['Blackberry Liftoff', 'Raspberry Tea', 'Lemonade'],
  },
  {
    slug: 'watermelon-bramble',
    name: 'Watermelon Bramble',
    collection: 'fall-berry-collection',
    color: '#E8F000',
    isNew: false,
    ingredients: ['Blackberry Liftoff', 'Raspberry Tea', 'Watermelon'],
  },
  {
    slug: 'pasion-berry-night',
    name: 'Passion Berry Night',
    collection: 'fall-berry-collection',
    color: '#FF3F72',
    isNew: false,
    ingredients: ['Blackberry Liftoff', 'Raspberry Tea', 'Passion fruit'],
  },
  {
    slug: 'blue-berry-a-plus',
    name: 'Berry Apple A-Plus',
    collection: 'school-fun-collection',
    color: '#FFE500',
    isNew: false,
    ingredients: ['Strawberry-watermelon', 'Grape'],
  },
  {
    slug: 'cloudberry-gossip',
    name: 'Cloudberry Gossip',
    collection: 'school-fun-collection',
    color: '#CDDC39',
    isNew: false,
    ingredients: ['Pink swirl', 'Marshmallow cloud', 'Blue raspberry'],
  },
  {
    slug: 'tropical-final-bell',
    name: 'Tropical Final Bell',
    collection: 'school-fun-collection',
    color: '#FF4081',
    isNew: false,
    ingredients: ['Blood orange', 'Passion fruit', 'Pineapple'],
  },
  {
    slug: 'green-candy-honors',
    name: 'Green Candy Honors',
    collection: 'school-fun-collection',
    color: '#A4C639',
    isNew: false,
    ingredients: ['Green apple', 'Cotton candy', 'Watermelon'],
  },
  {
    slug: 'rainbow-pop-quiz',
    name: 'Rainbow Pop Quiz',
    collection: 'school-fun-collection',
    color: '#E8F000',
    isNew: false,
    ingredients: ['Blue swirl', 'Green apple', 'Watermelon'],
  },
] as const;

export function getCollectionLabel(slug: FlavorCollectionSlug): string {
  return FLAVOR_COLLECTIONS.find((c) => c.slug === slug)?.name ?? slug;
}
